Contact/urls.py
from django.urls import path
from . import views
app_name = 'Contact'

urlpatterns = [
    path('', views.Contact.as_view(), name = 'Contact'),
]

EWSweb/urls.py
"""EWSweb URL Configuration

Các Apps trong Website:
    1. Home: Trang chủ
    2. EarlyWarningNote: Thông tin cảnh báo
    3. MonitoringData: Dữ liệu quan trắc
    4. TraningMaterial: Tài liệu hướng dẫn - tập huấn
    5. Contact: Thông tin liên hệ và quản lý account

Danh sách `urlpatterns` định tuyến URL đến các chế độ xem. Để biết thêm thông tin vui lòng xem:
     https://docs.djangoproject.com/en/4.0/topics/http/urls/
Ví dụ:
Chế độ xem chức năng
     1. Thêm nhập: từ chế độ xem nhập của my_app
     2. Thêm URL vào urlpatterns: path ('', views.home, name = 'home')
Chế độ xem dựa trên lớp
     1. Thêm nhập: from other_app.views import Trang chủ
     2. Thêm URL vào urlpatterns: path ('', Home.as_view (), name = 'home')
Bao gồm một URLconf khác
     1. Nhập hàm include (): từ django.urls nhập bao gồm, đường dẫn
     2. Thêm một URL vào urlpatterns: path ('blog /', include ('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('EarlyWarningNote', include('EarlyWarningNote.urls')),
    path('MonitoringData', include('MonitoringData.urls')),
    path('TrainingMaterial', include('TrainingMaterial.urls')),
    path('Contact', include('Contact.urls')),
    path('Register', include('Register.urls')),
    path('Upload', include('Upload.urls')),
]

EarlyWarningNote/urls.py
from django.urls import path
from . import views
app_name = 'EarlyWarningNote'
urlpatterns = [
    path('', views.EarlyWarningNote, name = 'EarlyWarningNote'),
]

Home/urls.py
from django.urls import path
from . import views
app_name = 'Home'
urlpatterns = [
    path('', views.index, name = "Home"),
]

MonitoringData/urls.py
from django.urls import path
from . import views
app_name = 'MonitoringData'
urlpatterns = [
    path('', views.MonitoringData, name = 'MonitoringData'),
]

Register/urls.py
from django.urls import path
from . import views
app_name = 'Register'

# Create your views here
urlpatterns = [
    path('', views.Register, name = 'Register'),
    path('getRegister/', views.getRegister, name = 'getRegister'),
]

TrainingMaterial/urls.py
from django.urls import path
from . import views
app_name = 'TrainingMaterial'
urlpatterns = [
    path('', views.TrainingMaterial, name = 'TrainingMaterial'),
]

Upload/urls.py
from django.urls import path
from . import views
app_name = 'Upload'

urlpatterns = [
    path('', views.index.as_view(), name = 'Upload'),
]

Contact/models.py
from django.db import models

EarlyWarningNote/models.py
from django.db import models

# Create your models here.

Home/models.py
from django.db import models

# Create your models here.

MonitoringData/models.py
from django.db import models

# Create your models here.

Register/models.py
from django.db import models

# Create your models here.
class Registermodel(models.Model):
	username = models.CharField(max_length = 25)
	email = models.EmailField()
	company = models.CharField(max_length = 25)
	phonenumber = models.CharField(max_length = 11)
	password = models.CharField(max_length = 13)
	address = models.CharField(max_length = 50)

	def __str__(self):
		return self.username

Upload/models.py
from django.db import models

# Create your models here.
class formUpload(models.Model):
	local = models.CharField(max_length = 25)
	hazard = models.CharField(max_length = 11)
	discribe = models.CharField(max_length = 30)
	image = models.FileField(upload_to='Media/')

	def __str__(self):
		return self.local

Contact/forms.py
from django import forms

class loginForm(forms.Form):
	username = forms.CharField(max_length = 25)
	password = forms.CharField(max_length = 13, widget = forms.PasswordInput)

Register/forms.py
from django import forms
from .models import Registermodel

class Registerform(forms.ModelForm):
	class Meta:
		model = Registermodel
		fields = ['username', 'email', 'company', 'phonenumber', 'password', 'address']

Upload/forms.py
from django import forms

class UploadMulti(forms.Form):
	local = forms.CharField(max_length = 25)
	hazard = forms.CharField(max_length = 11)
	discribe = forms.CharField(max_length = 30)
	image = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
	

 

Contact/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from .forms import loginForm

class Contact(View):
	def get(sefl, request):
		LF = loginForm
		return render(request, 'Contact/Contact.html', {'LF': LF})
	def post(seft, request):
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return render(request, 'Contact/Sendalarm.html')
		else:
			return HttpResponse('Đăng nhập không thành công')

EarlyWarningNote/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your Home views here.
def EarlyWarningNote(request):
	return render(request, 'EarlyWarningNote/EarlyWarningNote.html')

Home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your Home views here.
def index(request):
	return render(request, 'Home/index.html')

MonitoringData/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your Home views here.
def MonitoringData(request):
	return render(request, 'MonitoringData/MonitoringData.html')

# https://api.openweathermap.org/data/2.5/onecall?lat={22.338703}&lon={103.848252}&exclude={hourly}&appid={c797b4f25f10e0d6466d9c626c623120}

Register/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import Registerform
from .models import Registermodel

# Create your views here.
def Register(request):
	context = {'RF': Registerform}
	return render(request, 'Register/Register.html', context)
def getRegister(request):
	if request.method == "POST":
		RF = Registerform(request.POST)
		if RF.is_valid():
			saveRF = Registermodel(
				username = RF.cleaned_data['username'],
				email = RF.cleaned_data['email'],
				company = RF.cleaned_data['company'],
				phonenumber = RF.cleaned_data['phonenumber'],
				password = RF.cleaned_data['password'],
				address = RF.cleaned_data['address'])
			saveRF.save()
			return HttpResponse('Đăng kí thành công')
		else:
			return HttpResponse('Đăng kí không thành công')

TrainingMaterial/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your Home views here.
def TrainingMaterial(request):
	return render(request, 'TrainingMaterial/TrainingMaterial.html')

Upload/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import UploadMulti
from .models import formUpload
from django.views.generic.edit import FormView

class index(FormView):
	def get (self, request):
		form = UploadMulti
		return render(request, 'Upload/Upload.html', {'form': form})
	def post(self, request):
		form_class = UploadMulti
		form = self.get_form(form_class)
		files = request.FILES.getlist('image')
		if form.is_valid():
			for f in files:
				instance = formUpload(image=f)
				instance.save()
		return HttpResponse('Bạn đã gửi thông tin cảnh báo thành công, thông tin này sẽ được cán bộ xử lý ngay lập tức!')

Home/templates/Home/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Cảnh báo nguy cơ trượt lở - lũ bùn đá - lũ quét</title>
	<link href="../../static/Home/Logo_web.jpg" rel="shortcut icon">
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'Home/style.css' %}">

</head>

<body>
	<div data-collapse="tiny" data-animation="over-right" data-duration="400" data-easing="ease" data-easing2="ease" role="banner" class="navbar w-nav">
		<div  class="w-container">
			<a href="/" aria-current="page" class="logo w-nav-brand w--current">
			<div class="long-text">EWS community</div>			
			</a>

			<nav role="navigation" class="nav-menu w-nav-menu">
				<a href="{% url 'Home:Home' %}" aria-current="page" class="nav-link w-nav-link w--current">Trang chủ</a>
				<a href="{% url 'EarlyWarningNote:EarlyWarningNote' %}" aria-current="page" class="nav-link w-nav-link">Cảnh báo sớm</a>
				<a href="{% url 'MonitoringData:MonitoringData' %}" aria-current="page" class="nav-link w-nav-link">Quan trắc</a>
				<a href="{% url 'TrainingMaterial:TrainingMaterial' %}" aria-current="page" class="nav-link w-nav-link">Tài liệu tập huấn</a>
				<a href="{% url 'Contact:Contact' %}" aria-current="page" class="nav-link w-nav-link">Liên hệ</a>
				<a href="#" class="close-x w-hidden-main w-hidden-medium w-hidden-small">×</a>
			</nav>
			<div class="menu-button w-hidden-main w-hidden-medium w-hidden-small w-clearfix w-nav-button">
				<div class="menu-icon w-icon-nav-menu"></div>
				<div class="menu-link">MENU</div>
			</div>


			<a class="nav-account">Account: Admin</a>

			<a class="weather-logo" rel="noopener" target="_blank" aria-label="" title="" href="https://www.msn.com/vi-vn/weather/forecast/in-Th%E1%BB%A5y-Khu%C3%AA,H%C3%A0-N%E1%BB%99i?loc=eyJsIjoiVGjhu6V5IEtodcOqIiwiciI6IkjDoCBO4buZaSIsImMiOiJWaeG7h3QgTmFtIiwiaSI6IlZOIiwiZyI6InZpLXZuIiwieCI6MTA1LjgxOTk5OTY5NDgyNDIyLCJ5IjoyMS4wNDM1MDA5MDAyNjg1NTV9&amp;weadegreetype=C" data-t="{&quot;n&quot;:&quot;weather_link&quot;,&quot;b&quot;:1,&quot;d&quot;:&quot;https://www.msn.com/vi-vn/weather/forecast/in-Th%E1%BB%A5y-Khu%C3%AA,H%C3%A0-N%E1%BB%99i?loc=eyJsIjoiVGjhu6V5IEtodcOqIiwiciI6IkjDoCBO4buZaSIsImMiOiJWaeG7h3QgTmFtIiwiaSI6IlZOIiwiZyI6InZpLXZuIiwieCI6MTA1LjgxOTk5OTY5NDgyNDIyLCJ5IjoyMS4wNDM1MDA5MDAyNjg1NTV9&amp;weadegreetype=C&quot;,&quot;c.t&quot;:36,&quot;c.v&quot;:&quot;weather&quot;,&quot;c.c&quot;:&quot;today&quot;,&quot;c.hl&quot;:&quot;28°C&quot;}" style="display: flex;" aria-expanded="false">
				<div id="i_location" class="location-left dark-font-color" title="" style="display: flex;">Hà Nội, ngày _</div>
				<div id="current-time"></div>
				<script>
				    var curDate = new Date();					      
				    // Ngày hiện tại
				    var curDay = curDate.getDate();					 
				    // Tháng hiện tại
				    var curMonth = curDate.getMonth() + 1;					      
				    // Năm hiện tại
				    var curYear = curDate.getFullYear();					 
				    // Gán vào thẻ HTML
				    document.getElementById('current-time').innerHTML =" " +  curDay + "/" + curMonth + "/" + curYear;
					</script>
				<div class="weather-glyph-location text-wrapper-image-hidden">
					<img class="icon-svg" src="https://assets.msn.com/weathermapdata/1/static/svg/72/v2/card/CloudyV3.svg" alt="Có mây">
				</div>
				<div class="weather-temperature"><span class="weather-text-location-left dark-font-color">‎28‎‎°C‎</span></div>
			</a>

		</div>
	</div>

	<div class="hero-section wf-section">
		<div class="hero-content w-container">
			<div style="-webkit-transform:translate3d(0, -30PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, -30PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, -30PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, -30PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);opacity:0" class="hero-heading">Let's do it together.</div>
			<div style="opacity:0;-webkit-transform:translate3d(0, 30PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 30PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 30PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 30PX, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0)" class="hero-subheading">We travel the world in search of stories. Come along for the ride.</div>
			<a href="#Latest-post" style="opacity:0" class="button w-button">View Latest Posts</a>
		</div>
	</div>


	<div class="content">
		{% block content %}

		{% endblock %}
	</div>
</body>
</html>


<!--

Home/templates/Home/index.html
<!--

	* Phiên bản thử nghiệm Website cảnh báo sớm có sự tham gia của cộng đồng Ver 1.0
	* Bản quyền thuộc sản phẩm đề tài ĐTĐL.CN 78.21	

-->

<!DOCTYPE html>
<html>
<head>
	<title>Hệ thống cảnh báo sớm có sự tham gia của cộng đồng</title>
	{% extends 'Home/base.html' %}
</head>	

{% block content %}
<body onLoad="initialize()">
	<div id="posts" class="main-section bottom-padding wf-section">
		<div id="Latest-post" class="w-container">
			<div class="section-heading">
				<h2 class="section-title">BẢN ĐỒ CẢNH BÁO CÁC KHU VỰC NGHIÊN CỨU CHI TIẾT</h2>
				<div class="med-divider"></div>
			</div>
			
			<div class="w-dyn-list" style="text-align: center; display: block;">
				<div role="list" class="w-clearfix w-dyn-items w-row">
					<iframe
						width="650"
						height="450"
						frameborder="0" style="border:0"
						loading="lazy" allowfullscreen
						src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDaX6l5GG3SRAmR3iHvINd2oolA4a0tGUU&q=Bản Rịa, Hà Giang, Vietnam&center=22.445562,104.482997&zoom=13&maptype=satellite">
					</iframe>
				</div>
				<div role="list">
					<iframe
						width="650"
						height="450"
						frameborder="0" style="border:0"
						loading="lazy" allowfullscreen
						src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDaX6l5GG3SRAmR3iHvINd2oolA4a0tGUU&q=Cát Thịnh, Yên Bái, Vietnam&center=21.491580,104.678683&zoom=13&maptype=satellite">
					</iframe>
				</div>				
				<div role="list">
					<iframe
						width="650"
						height="450"
						frameborder="0" style="border:0"
						loading="lazy" allowfullscreen
						src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDaX6l5GG3SRAmR3iHvINd2oolA4a0tGUU&q=Chiềng Đông, Yên Châu, Sơn La, Vietnam&center=21.120142,104.239673&zoom=13&maptype=satellite">
					</iframe>
				</div>
			</div>
		</div>
	</div>

	<div id="posts" class="wf-section">
		<div id="Latest-post" class="w-container">
			<div class="section-heading">
				<h2 class="section-title">MỘT SỐ KHU VỰC CẦN CẢNH GIÁC TRONG 24 GIỜ TỚI</h2>
				<div class="med-divider"></div>
			</div>
			<br>
			<a href='' target='_blank' style="text-align: center; display: block;"><img src="../../static/Home/Bang thong ke khu vuc nguy hiem thien tai.jpg"/></a>
		</div>
	</div>

	<div class="main-section bottom-padding w-container">
		<div class="section-heading">
			<h2 class="section-title">TIN TỨC PHÒNG CHỐNG THIÊN TAI</h2>
			<div class="med-divider"></div>
		</div>
		<div class="w-dyn-list">
			<div role="list" class="w-clearfix w-dyn-items w-row">
				<div role="listitem" class="blog-thumbnail w-dyn-item w-col w-col-4">
					<a href="https://baotainguyenmoitruong.vn/kiem-tra-cong-tac-ung-pho-khac-phuc-hau-qua-sat-lo-dat-tai-thai-nguyen-340438.html" class="thumbnail-wrapper w-inline-block">
						<div style="background-image: url(&quot;https://btnmt.1cdn.vn/2022/05/31/1(4).jpg&quot;); transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d;" class="thumbnail-image image-wrapper"></div>
						<div class="thumbnail-text">
							<div class="blog-title">Công tác tái thiết sau thiên tai</div>
							<div class="preview-text">Kiểm tra công tác ứng phó, khắc phục hậu quả sạt lở đất tại Thái Nguyên</div>
						</div>
						<div class="thumb-details w-clearfix">
							<div class="author-title">Nguồn: Báo tài nguyên và Môi trường</div>
							<div class="thumbnail-date">31/05/2022</div>
						</div>
					</a>
				</div>
				
				<div role="listitem" class="blog-thumbnail w-dyn-item w-col w-col-4">
					<a href="https://vtv.vn/xa-hoi/yen-bai-tinh-lo-172-van-chua-thong-tuyen-sau-6-ngay-sat-lo-20220607000653729.htm" class="thumbnail-wrapper w-inline-block">
						<div style="background-image: url(&quot;https://vtv1.mediacdn.vn/thumb_w/640/2022/6/7/vnapotalyenbaiduongtinhlo172vanchuaduocthongtuyensau6ngaysatlo1205497866155426-1654534953697118518675.jpg&quot;); transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d;" class="thumbnail-image image-wrapper"></div>
						<div class="thumbnail-text">
							<div class="blog-title">Thông tin thiệt hại</div>
							<div class="preview-text">Tỉnh lộ 172 vẫn chưa thông tuyến sau 6 ngày sạt lở</div>
						</div>
						<div class="thumb-details w-clearfix">
							<div class="author-title">Nguồn: VTV Điện tử</div>
							<div class="thumbnail-date">07/06/2022</div>
						</div>
					</a>
				</div>
				
				<div role="listitem" class="blog-thumbnail w-dyn-item w-col w-col-4">
					<a href="https://vnanet.vn/vi/anh/anh-thoi-su-trong-nuoc-1014/son-la-can-som-di-chuyen-gan-70-ho-dan-vung-nguy-co-sat-lo-o-ban-na-pan-yen-chau-5550780.html" class="thumbnail-wrapper w-inline-block">
						<div style="background-image: url(&quot;https://vnanet.vn/Data/Articles/2021/07/12/5550771/vna_potal_son_la_can_som_di_chuyen_gan_70_ho_dan_vung_nguy_co_sat_lo_o_ban_na_pan_yen_chau_stand.jpg&quot;); transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d;" class="thumbnail-image image-wrapper"></div>
						<div class="thumbnail-text">
							<div class="blog-title">Cảnh báo khu vực nguy hiểm</div>
							<div class="preview-text">Điểm lở đá nguy hiểm tại xã Chiềng Đông</div>
						</div>
						<div class="thumb-details w-clearfix">
							<div class="author-title">Nguồn: TTX Việt Nam</div>
							<div class="thumbnail-date">12/07/2021</div>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>

	<div class="w-container">
		<div class="section-heading">
			<h2 class="section-title">CÁC CƠ QUAN PHỐI HỢP THỰC HIỆN ĐỀ TÀI ĐTĐL.CN 78.21</h2>
			<div class="med-divider"></div>
		</div>
		<div class="w-dyn-list">
			<div role="list" class="w-clearfix w-dyn-items w-row">
				<div role="listitem" class="w-dyn-item w-col w-col-4">
					<a href="https://www.hust.edu.vn/">
						<div style="background-image: url(&quot;../../static/Home/Logo_DH Bach Khoa.png&quot;); transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d;" class="thumbnail-image image-wrapper">							
						</div>
					</a>
				</div>
				
				<div role="listitem" class="w-dyn-item w-col w-col-4">
					<a href="https://www.facebook.com/phongchongthientaivn">
						<div style="background-image: url(&quot;../../static/Home/Logo_Vu cong dong facebook.jpg&quot;); transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d; " class="thumbnail-image image-wrapper">
						</div>
					</a>
				</div>
				
				<div role="listitem" class="w-dyn-item w-col w-col-4">
					<a href="http://igsvn.vn/">
						<div style="background-image: url(&quot;../../static/Home/Logo_VDC.jpg&quot;); transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d; " class="thumbnail-image image-wrapper">
						</div>
					</a>
				</div>

				<div class="thumbnail-text">
							<div class="blog-title"></div>
							<div class="preview-text"></div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}
</body>
<html>