Contact/urls.py
from django.urls import path
from . import views
app_name = 'Contact'

urlpatterns = [
    path('', views.Contact.as_view(), name = 'Contact'),
]

EWSweb/urls.py
"""EWSweb URL Configuration

Các Apps trong Website:
    1. Home: Trang chủ
    2. EarlyWarningNote: Thông tin cảnh báo
    3. MonitoringData: Dữ liệu quan trắc
    4. TraningMaterial: Tài liệu hướng dẫn - tập huấn
    5. Contact: Thông tin liên hệ và quản lý account

Danh sách `urlpatterns` định tuyến URL đến các chế độ xem. Để biết thêm thông tin vui lòng xem:
     https://docs.djangoproject.com/en/4.0/topics/http/urls/
Ví dụ:
Chế độ xem chức năng
     1. Thêm nhập: từ chế độ xem nhập của my_app
     2. Thêm URL vào urlpatterns: path ('', views.home, name = 'home')
Chế độ xem dựa trên lớp
     1. Thêm nhập: from other_app.views import Trang chủ
     2. Thêm URL vào urlpatterns: path ('', Home.as_view (), name = 'home')
Bao gồm một URLconf khác
     1. Nhập hàm include (): từ django.urls nhập bao gồm, đường dẫn
     2. Thêm một URL vào urlpatterns: path ('blog /', include ('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('EarlyWarningNote', include('EarlyWarningNote.urls')),
    path('MonitoringData', include('MonitoringData.urls')),
    path('TrainingMaterial', include('TrainingMaterial.urls')),
    path('Contact', include('Contact.urls')),
    path('Register', include('Register.urls')),
    path('Upload', include('Upload.urls')),
]

EarlyWarningNote/urls.py
from django.urls import path
from . import views
app_name = 'EarlyWarningNote'
urlpatterns = [
    path('', views.EarlyWarningNote, name = 'EarlyWarningNote'),
]

Home/urls.py
from django.urls import path
from . import views
app_name = 'Home'
urlpatterns = [
    path('', views.index, name = "Home"),
]

MonitoringData/urls.py
from django.urls import path
from . import views
app_name = 'MonitoringData'
urlpatterns = [
    path('', views.MonitoringData, name = 'MonitoringData'),
]

Register/urls.py
from django.urls import path
from . import views
app_name = 'Register'

# Create your views here
urlpatterns = [
    path('', views.Register, name = 'Register'),
    path('getRegister/', views.getRegister, name = 'getRegister'),
]

TrainingMaterial/urls.py
from django.urls import path
from . import views
app_name = 'TrainingMaterial'
urlpatterns = [
    path('', views.TrainingMaterial, name = 'TrainingMaterial'),
]

Upload/urls.py
from django.urls import path
from . import views
app_name = 'Upload'

urlpatterns = [
    path('', views.index.as_view(), name = 'Upload'),
]

Contact/models.py
from django.db import models

EarlyWarningNote/models.py
from django.db import models

# Create your models here.

Home/models.py
from django.db import models

# Create your models here.

MonitoringData/models.py
from django.db import models

# Create your models here.

Register/models.py
from django.db import models

# Create your models here.
class Registermodel(models.Model):
	username = models.CharField(max_length = 25)
	email = models.EmailField()
	company = models.CharField(max_length = 25)
	phonenumber = models.CharField(max_length = 11)
	password = models.CharField(max_length = 13)
	address = models.CharField(max_length = 50)

	def __str__(self):
		return self.username

TrainingMaterial/models.py
from django.db import models

# Create your models here.

Upload/models.py
from django.db import models

# Create your models here.
class formUpload(models.Model):
	local = models.CharField(max_length = 25)
	hazard = models.CharField(max_length = 11)
	discribe = models.CharField(max_length = 30)
	image = models.FileField(upload_to='Media/')

	def __str__(self):
		return self.local

Contact/forms.py
from django import forms

class loginForm(forms.Form):
	username = forms.CharField(max_length = 25)
	password = forms.CharField(max_length = 13, widget = forms.PasswordInput)

Register/forms.py
from django import forms
from .models import Registermodel

class Registerform(forms.ModelForm):
	class Meta:
		model = Registermodel
		fields = ['username', 'email', 'company', 'phonenumber', 'password', 'address']

Upload/forms.py
from django import forms

class UploadMulti(forms.Form):
	local = forms.CharField(max_length = 25)
	hazard = forms.CharField(max_length = 11)
	discribe = forms.CharField(max_length = 30)
	image = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
	

 

Contact/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from .forms import loginForm

class Contact(View):
	def get(sefl, request):
		LF = loginForm
		return render(request, 'Contact/Contact.html', {'LF': LF})
	def post(seft, request):
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return render(request, 'Contact/Sendalarm.html')
		else:
			return HttpResponse('Đăng nhập không thành công')

EarlyWarningNote/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your Home views here.
def EarlyWarningNote(request):
	return render(request, 'EarlyWarningNote/EarlyWarningNote.html')

Home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your Home views here.
def index(request):
	return render(request, 'Home/index.html')

MonitoringData/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your Home views here.
def MonitoringData(request):
	return render(request, 'MonitoringData/MonitoringData.html')

# https://api.openweathermap.org/data/2.5/onecall?lat={22.338703}&lon={103.848252}&exclude={hourly}&appid={c797b4f25f10e0d6466d9c626c623120}

Register/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import Registerform
from .models import Registermodel

# Create your views here.
def Register(request):
	context = {'RF': Registerform}
	return render(request, 'Register/Register.html', context)
def getRegister(request):
	if request.method == "POST":
		RF = Registerform(request.POST)
		if RF.is_valid():
			saveRF = Registermodel(
				username = RF.cleaned_data['username'],
				email = RF.cleaned_data['email'],
				company = RF.cleaned_data['company'],
				phonenumber = RF.cleaned_data['phonenumber'],
				password = RF.cleaned_data['password'],
				address = RF.cleaned_data['address'])
			saveRF.save()
			return HttpResponse('Đăng kí thành công')
		else:
			return HttpResponse('Đăng kí không thành công')

TrainingMaterial/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your Home views here.
def TrainingMaterial(request):
	return render(request, 'TrainingMaterial/TrainingMaterial.html')

Upload/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import UploadMulti
from .models import formUpload
from django.views.generic.edit import FormView

class index(FormView):
	def get (self, request):
		form = UploadMulti
		return render(request, 'Upload/Upload.html', {'form': form})
	def post(self, request):
		form_class = UploadMulti
		form = self.get_form(form_class)
		files = request.FILES.getlist('image')
		if form.is_valid():
			for f in files:
				instance = formUpload(image=f)
				instance.save()
		return HttpResponse('Bạn đã gửi thông tin cảnh báo thành công, thông tin này sẽ được cán bộ xử lý ngay lập tức!')

Contact/templates/Contact/Contact.html
<!DOCTYPE html>
<html>
<head>
	<title>Liên hệ, cung cấp thông tin cảnh báo</title>
<head>

{% extends 'Home/base.html' %}

<body>
{% block content %}
	<div id="posts" class="wf-section">
		<div id="Latest-post" class="w-container">
			<div class="section-heading">
				<h2 class="section-title">THÔNG TIN LIÊN HỆ TRONG TRƯỜNG HỢP KHẨN CẤP</h2>
				<div class="med-divider"></div>
			</div>
			<br>
			<ul class="blog-title" style="color: black; padding-bottom: 57px;">
				<li>Đường dây nóng TC PCTT: 024.37333.3664 - 024.3734.9821</li>
				<li>Facebook: https://www.facebook.com/phongchongthientaivn</li>
				<li>Vụ Quản lý thiên tai cộng đồng: 024.3733.5804</li>
				<li>Đề tài cấp nhà nước ĐTĐL 78/21: 039.9750.875</li>
				<li>Email: canhbaothientaicongdong@gmail.com</li>
			</ul>
		</div>
	</div>

	<div class="main-section bottom-padding w-container">
		<div class="section-heading">
			<h2 class="section-title">CỘNG ĐỒNG GỬI THÔNG TIN CẢNH BÁO</h2>
			<div class="med-divider"></div>
		</div>
		<form action="{% url 'Contact:Contact'%}" method="post" style="text-align: center; display: block;">
			{% csrf_token %}
			{{LF.as_p}}
			<input type="Submit">
		</form>	
	</div>

	<div id="posts" class="wf-section">
		<div id="Latest-post" class="w-container">
			<div class="section-heading">
				<h2 class="section-title">ĐĂNG NHẬP</h2>
				<div class="med-divider"></div>
			</div>
			<br>
			<form action="{% url 'Contact:Contact'%}" method="post" style="text-align: center; display: block; padding-bottom: 57px;">
				{% csrf_token %}
				{{LF.as_p}}
				<input type="Submit">
			</form>	
		</div>
	</div>

	<div class="main-section bottom-padding w-container">
		<div class="section-heading">
			<h2 class="section-title">ĐĂNG KÍ THÀNH VIÊN</h2>
			<div class="med-divider"></div>
		</div>
		<form action="{% url 'Contact:Contact'%}" method="post" style="text-align: center; display: block;">
			{% csrf_token %}
			{{LF.as_p}}
			<input type="Submit">
		</form>	
	</div>

{% endblock %}
</body>
</html>

EarlyWarningNote/templates/EarlyWarningNote/EarlyWarningNote.html
<!DOCTYPE html>
<html>
<head>
	<title>Biện pháp ứng phó</title>
<head>

{% extends 'Home/base.html' %}

<body>
{% block content %}
	<div id="posts" class="main-section bottom-padding wf-section">
		<div id="Latest-post" class="w-container">
			<div class="section-heading">
				<h2 class="section-title">TIMELINE CẢNH BÁO NGUY CƠ TAI BIẾN TRƯỢT LỞ - LŨ BÙN ĐÁ - LŨ QUÉT <br> TẠI 3 KHU VỰC NGHIÊN CỨU CHI TIẾT </h2>
				<div class="med-divider"></div>
			</div>	
			<div class="w-dyn-list" style="text-align: center; display: block;">
				<div role="list" class="w-clearfix w-dyn-items w-row">
					<h4 class="blog-title">TIMELINE CẢNH BÁO NGUY CƠ TAI BIẾN XÃ BẢN RỊA - HÀ GIANG</h4><br>
					<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/nhnGd3H4/Timeline-of-Disaster-Related-Flickr-Activity.jpg' border='0' alt='Timeline-of-Disaster-Related-Flickr-Activity'/></a>
				</div>
				<div role="list">
					<h4 class="blog-title">TIMELINE CẢNH BÁO NGUY CƠ TAI BIẾN XÃ CẤT THỊNH - YÊN BÁI</h4><br>
					<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/nhnGd3H4/Timeline-of-Disaster-Related-Flickr-Activity.jpg' border='0' alt='Timeline-of-Disaster-Related-Flickr-Activity'/></a>
				</div>
				<div role="list">
					<h4 class="blog-title">TIMELINE CẢNH BÁO NGUY CƠ TAI BIẾN XÃ CHIỀNG ĐÔNG - SƠN LA</h4><br>
					<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/nhnGd3H4/Timeline-of-Disaster-Related-Flickr-Activity.jpg' border='0' alt='Timeline-of-Disaster-Related-Flickr-Activity'/></a>
				</div>		
			</div>
		</div>
	</div>

	<div id="posts" class="wf-section">
		<div id="Latest-post" class="w-container">
			<div class="section-heading">
				<h2 class="section-title">DỰ BÁO NGUY CƠ TRƯỢT LỞ THEO CÁC KHOẢNG THỜI GIAN</h2>
				<div class="med-divider"></div>
			</div>
			<br>
			<a href='https://postimages.org/' target='_blank' style="text-align: center; display: block;"><img src='https://i.postimg.cc/mDP8dcLh/Forecast-landslide-2022-07-31.jpg' border='0' alt='Forecast-landslide-2022-07-31'/></a>
		</div>
	</div>

	<div id="posts" class="main-section bottom-padding wf-section">
		<div id="Latest-post" class="w-container">
			<div class="section-heading">
				<h2 class="section-title">SỐ LIỆU KHÍ TƯỢNG PHỤC VỤ CẢNH BÁO SỚM</h2>
				<div class="med-divider"></div>
			</div>
			<div class="w-dyn-list" style="text-align: center; display: block;">
				<div role="list" class="w-clearfix w-dyn-items w-row">
					<h4 class="blog-title">DỮ LIỆU ẢNH RADAR MÂY VỆ TINH - NGUỒN VENTUSKY</h4>
					<iframe
						width="650"
						height="450"
						frameborder="0" style="border:0"
						loading="lazy" allowfullscreen
						src="https://www.ventusky.com/?p=20.18;106.14;5&l=radar">
					</iframe>
				</div>
				<div role="list">
					<h4 class="blog-title">DỰ BÁO MƯA TRONG 12 GIỜ TỚI - NGUỒN WINDY.COM</h4>
					<iframe
						width="650"
						height="450"
						frameborder="0" style="border:0"
						loading="lazy" allowfullscreen
						src="https://embed.windy.com/embed2.html?lat=20.283&lon=107.095&detailLat=21.031&detailLon=105.852&width=650&height=450&zoom=6&level=surface&overlay=rain&product=ecmwf&menu=&message=&marker=&calendar=12&pressure=&type=map&location=coordinates&detail=&metricWind=default&metricTemp=default&radarRange=-1">
					</iframe>
				</div>				
			</div>
		</div>
	</div>


{% endblock %}
</body>
</html>

MonitoringData/templates/MonitoringData/MonitoringData.html
<!DOCTYPE html>
<html>
<head>
	<title>Dữ liệu quan trắc</title>
<head>

{% extends 'Home/base.html' %}

<body>
{% block content %}
	<div id="posts" class="main-section bottom-padding wf-section">
		<div id="Latest-post" class="w-container">
			<div class="section-heading">
				<h2 class="section-title">HỆ THỐNG QUAN TRẮC TẠI XÃ BẢN RỊA - QUANG BÌNH - HÀ GIANG</h2>
				<div class="med-divider"></div>
			</div>	
			<div class="w-dyn-list" style="text-align: center; display: block;">
				<div role="list" class="w-clearfix w-dyn-items w-row">
					<h4 class="blog-title">DIỄN BIẾN MƯA GIỜ</h4><br>
					<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/nhnGd3H4/Timeline-of-Disaster-Related-Flickr-Activity.jpg' border='0' alt='Timeline-of-Disaster-Related-Flickr-Activity'/></a>
				</div>
				<div role="list">
					<h4 class="blog-title">DIỄN BIẾN MỰC NƯỚC SUỐI</h4><br>
					<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/nhnGd3H4/Timeline-of-Disaster-Related-Flickr-Activity.jpg' border='0' alt='Timeline-of-Disaster-Related-Flickr-Activity'/></a>
				</div>
				<div role="list">
					<h4 class="blog-title">DIỄN BIẾN ÁP LỰC NƯỚC LỖ RỖNG TRÊN SƯỜN LA</h4><br>
					<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/nhnGd3H4/Timeline-of-Disaster-Related-Flickr-Activity.jpg' border='0' alt='Timeline-of-Disaster-Related-Flickr-Activity'/></a>
				</div>
				<div role="list">
					<h4 class="blog-title">DIỄN BIẾN RUNG ĐỘNG NỀN XÁC ĐỊNH BẰNG GEOPHONE</h4><br>
					<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/nhnGd3H4/Timeline-of-Disaster-Related-Flickr-Activity.jpg' border='0' alt='Timeline-of-Disaster-Related-Flickr-Activity'/></a>
				</div>
				<div role="list">
					<h4 class="blog-title">HÌNH ẢNH GIÁM SÁT SUỐI BẰNG CAMERA</h4><br>
					<iframe
						width="640"
						height="360"
						frameborder="0" style="border:0"
						loading="lazy" allowfullscreen
						src="https://www.youtube.com/embed/y7e-GC6oGhg">
					</iframe>
				</div>			
			</div>
		</div>
	</div>

	<div id="posts" class="main-section bottom-padding wf-section">
		<div id="Latest-post" class="w-container">
			<div class="section-heading">
				<h2 class="section-title">HỆ THỐNG QUAN TRẮC TẠI XÃ CÁT THỊNH - VĂN CHẤN - YÊN BÁI</h2>
				<div class="med-divider"></div>
			</div>	
			<div class="w-dyn-list" style="text-align: center; display: block;">
				<div role="list" class="w-clearfix w-dyn-items w-row">
					<h4 class="blog-title">DIỄN BIẾN MƯA GIỜ</h4><br>
					<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/nhnGd3H4/Timeline-of-Disaster-Related-Flickr-Activity.jpg' border='0' alt='Timeline-of-Disaster-Related-Flickr-Activity'/></a>
				</div>		
			</div>
		</div>
	</div>

	<div id="posts" class="main-section bottom-padding wf-section">
		<div id="Latest-post" class="w-container">
			<div class="section-heading">
				<h2 class="section-title">HỆ THỐNG QUAN TRẮC TẠI XÃ CHIỀNG ĐÔNG - YÊN CHÂU - SƠN LA</h2>
				<div class="med-divider"></div>
			</div>	
			<div class="w-dyn-list" style="text-align: center; display: block;">
				<div role="list" class="w-clearfix w-dyn-items w-row">
					<h4 class="blog-title">DIỄN BIẾN MƯA GIỜ</h4><br>
					<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/nhnGd3H4/Timeline-of-Disaster-Related-Flickr-Activity.jpg' border='0' alt='Timeline-of-Disaster-Related-Flickr-Activity'/></a>
				</div>		
			</div>
		</div>
	</div>
{% endblock %}
</body>
</html>

Register/templates/Register/Register.html
<!DOCTYPE html>
<html>
<head>
	<title>Đăng kí thành viên mới</title>
<head>

{% extends 'Home/base.html' %}

<body>
{% block content %}
<div style="color:green">
	<h4>ĐĂNG KÍ</h4>
	<form action="{% url 'Register:Register'%}" method="POST">
		{% csrf_token %}
		{{RF.as_p}}
		<input type="Submit">
	</form>	
</div>
{% endblock %}
</body>
</html>

TrainingMaterial/templates/TrainingMaterial/TrainingMaterial.html
<!DOCTYPE html>
<html>
<head>
	<title>Tài liệu hướng dẫn cho cộng đồng</title>
<head>

{% extends 'Home/base.html' %}

<body>
{% block content %}
	<div class="main-section bottom-padding w-container">
		<div class="section-heading">
			<h2 class="section-title">MỘT SỐ HOẠT ĐỘNG PCTT TIÊU BIỂU CỦA CỘNG ĐỒNG</h2>
			<div class="med-divider"></div>
		</div>
		<div class="w-dyn-list">
			<div role="list" class="w-clearfix w-dyn-items w-row">
				<div role="listitem" class="blog-thumbnail w-dyn-item w-col w-col-4">
					<a href="/blog/still-standing-tall" data-w-id="46150442-4efa-9d36-3a4c-20d527e7a6bc" class="thumbnail-wrapper w-inline-block">
						<div style="background-image: url(&quot;https://assets.website-files.com/5e4b1929fccc7f96f6de825d/5e4b1929fccc7f8ce9de833d_photo-1433854304641-67729357fe18.jpg&quot;); transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d;" class="thumbnail-image image-wrapper"></div>
						<div class="thumbnail-text">
							<div class="blog-title">Báo cáo tuần</div>
							<div class="preview-text">Tổng thiệt hại do thiên tai đến ngày 31/07/2022.</div>
						</div>
						<div class="thumb-details w-clearfix">
							<div class="author-title">Nguồn: TC PCTT</div>
							<div class="thumbnail-date">31/07/2022</div>
						</div>
					</a>
				</div>
				
				<div role="listitem" class="blog-thumbnail w-dyn-item w-col w-col-4">
					<a href="/blog/sunny-side-up" data-w-id="46150442-4efa-9d36-3a4c-20d527e7a6bc" class="thumbnail-wrapper w-inline-block">
						<div style="background-image: url(&quot;https://assets.website-files.com/5e4b1929fccc7f96f6de825d/5e4b1929fccc7f7caade8338_photo-1431329842981-433c8635c2b9.jpg&quot;); transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d;" class="thumbnail-image image-wrapper"></div>
						<div class="thumbnail-text">
							<div class="blog-title">Tin tức cảnh báo</div>
							<div class="preview-text">Bản tin cảnh báo thiên tai số 5.</div>
						</div>
						<div class="thumb-details w-clearfix">
							<div class="author-title">Nguồn: TC PCTT</div>
							<div class="thumbnail-date">21/07/2022</div>
						</div>
					</a>
				</div>
				
				<div role="listitem" class="blog-thumbnail w-dyn-item w-col w-col-4">
					<a href="/blog/water-falls" data-w-id="46150442-4efa-9d36-3a4c-20d527e7a6bc" class="thumbnail-wrapper w-inline-block">
						<div style="background-image: url(&quot;https://assets.website-files.com/5e4b1929fccc7f96f6de825d/5e4b1929fccc7f1017de8349_photo-1433155327100-12aac6a14ff1.jpg&quot;); transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d;" class="thumbnail-image image-wrapper"></div>
						<div class="thumbnail-text">
							<div class="blog-title">Chia sẻ kinh nghiệm về PCCT</div>
							<div class="preview-text">Kinh nghiệm về PCCT của xã Cát Thịnh.</div>
						</div>
						<div class="thumb-details w-clearfix">
							<div class="author-title">Nguồn: BCH PCTT Yên Bái</div>
							<div class="thumbnail-date">05/07/2022</div>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>

	<div id="posts" class="wf-section">
		<div id="Latest-post" class="w-container">
			<div class="section-heading">
				<h2 class="section-title">TÀI LIỆU HƯỚNG DẪN CẢNH BÁO SỚM DỰA VÀO CỘNG ĐỒNG</h2>
				<div class="med-divider"></div>
			</div>
			<br>
			<ul class="blog-title" style="color: black; padding-bottom: 57px;">
				<li><a href= " https://phongchongthientai.mard.gov.vn/Pages/Tai-lieu-truyen-thong-pctt.aspx "target="_blank" style="color: black;"> Tài liệu truyền thông về Phòng chống thiên tai </a></li>
				<li><a href= " http://www.vncold.vn/Modules/CMS/Upload/10/KhoaHocCongNghe/160108/DrPhuc_VinAWARE.pdf "target="_blank" style="color: black;"> Hướng dẫn sử dụng hệ thống cảnh báo sớm dựa vào cộng đồng thôn bản </a></li>
				<li><a href= " https://baochinhphu.vn/bo-y-te-huong-dan-phan-loai-4-cap-do-dich-102302137.htm "target="_blank" style="color: black;"> Bộ tiêu chí các cấp báo động tích hợp tai biến </a></li>
				<li><a href= " https://vncdc.gov.vn/huong-dan-cach-ly-y-te-tai-nha-noi-luu-tru-de-phong-chong-benh-covid-19-nd15558.html "target="_blank" style="color: black;"> Quy trình báo động và ứng phó tai biến cấp thôn bản </a></li>
			</ul>
		</div>
	</div>

	<div class="main-section bottom-padding w-container">
		<div class="section-heading">
			<h2 class="section-title">VIDEO HƯỚNG DẪN PCTT CÓ SỰ THAM GIA CỦA CỘNG ĐỒNG</h2>
			<div class="med-divider"></div>
		</div>
		<div style="text-align: center; display: block;">
			<iframe width="640" height="360" src="https://www.youtube.com/embed/_aghWPzkB7M"></iframe><br>
			<iframe width="640" height="360" src="https://www.youtube.com/embed/Us-TVg40ExM"></iframe><br>
			<iframe width="640" height="360" src="https://www.youtube.com/embed/IIudaL1fzEk"></iframe>
		</div>
	</div>
{% endblock %}
</body>
</html>

Upload/templates/Upload/Upload.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Cộng đồng cảnh báo</title>
	<link rel="stylesheet" href="">
<head>

{% extends 'Home/base.html' %}

<body>
{% block content %}
<div style="color:black">
	<h4>CỘNG ĐỒNG GỬI THÔNG TIN CẢNH BÁO</h4>
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<input type="Submit">
	</form>		
</div>

{% endblock %}
</body>
</html>